name: azure-test

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - '**'

jobs:
  start-runner:
    environment: ci
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-runner.outputs.label }}
      instance-id: ${{ steps.start-runner.outputs.instance-id }}
    steps:
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: Canner/ec2-github-runner@feature/azure
        name: start runner
        id: start-runner
        with:
          mode: start
          cloud: azure
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          azure-location: 'Japan East'
          azure-vm-size: 'Standard_D2s_v3'
          azure-network-interface: ${{ secrets.AZURE_NETWORK_INTERFACE }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          azure-image-id: ${{ secrets.AZURE_IMAGE_ID }}
          azure-network-security-group: ${{ secrets.AZURE_NETWORK_SECURITY_GROUP }}
  test:
    needs:
      - start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.14
      - name: test
        run: | 
          docker pull testcontainers/ryuk:0.3.0
          docker image ls
  stop-runner:
    environment: ci
    needs:
      - start-runner
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: Canner/ec2-github-runner@feature/azure
        name: stop runner
        with:
          mode: stop
          cloud: azure
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          instance-id: ${{ needs.start-runner.outputs.instance-id }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
